---
- hosts: web
  become: yes
  tasks:
  - name: Download and Extract WorPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/
      remote_user: yes  
  - name: Extract wordpress
    unarchive:
     src: /var/www/wordpress.tar.gz
     dest: /var/www/
     copy: no
  - name: rename derectory
    command: "mv /var/www/wordpress /var/www/nguyendai.com"
  - name: move derectory
    command: " mv /var/www/nguyendai.com/wp-config-sample.php /var/www/nguyendai.com/wp-config.php"
  - name: Change owner and mode
    file:
     path: /var/www/nguyendai.com
     owner: www-data
     group: www-data
     recurse: yes
     state: directory
     mode: '0755'
     - name: Copy and edit file wp-config.php
    template:
      src: /home/daitq1998/wordpress-playbook/roles/config/wp-config.php
      dest: /var/www/nguyendai.com/wp-config.php
      backup: yes
  - name: Copy and edit file
    template:
      src: /home/daitq1998/wordpress-playbook/roles/config/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
      backup: yes
    notify: restart apache2
  - name: add hosts db
    become: yes
    become_user: root
    shell: echo "192.168.122.221 daina" >> /etc/hosts
  - name: add web-server hosts
    become: yes
    become_user: root
    shell: echo "192.168.122.148 nguyendai.com" >> /etc/hosts
    when: "'anhdai' in inventory_hostname"
  - name: add web-server2 hosts
    become: yes
    become_user: root
    shell: echo "192.168.122.95 nguyendai.com" >> /etc/hosts
    when: "'daitq' in inventory_hostname"
  handlers:
     - name: restart apache2
       service: 
        name: apache2
        state: restarted
